"""Copies the UpToDate page scripts from the Android app (UtdClient.java) into the iPhone app
(DermScholar/UtdScripts.swift), so both read UpToDate the same way. Run after changing them:
python3 ios/gen-utd-scripts.py"""
import os, re

here = os.path.dirname(os.path.abspath(__file__))
java = open(os.path.join(here, '..', 'app/src/main/java/org/research4life/portal/UtdClient.java')).read()
names = ['PRO_SCRIPT', 'HINT_SCRIPT', 'CONTINUE_SCRIPT', 'SEARCH_SCRIPT', 'TOPIC_SCRIPT']
out = ['// Generated by ios/gen-utd-scripts.py from the Android app\'s UtdClient.java: do not edit.', '', 'enum UtdScripts {']
for n in names:
    m = re.search(r'static final String ' + n + r' = (.*?);\n', java, re.S)
    parts = re.findall(r'"((?:[^"\\]|\\.)*)"', m.group(1))
    # Java escapes (\\ \" \n) only; other characters (— “) stay as they are.
    js = ''.join(re.sub(r'\\(.)', lambda e: {'n': '\n', 't': '\t'}.get(e.group(1), e.group(1)), p) for p in parts)
    assert '"#' not in js
    name = {'CONTINUE': 'proceed'}.get(n.split('_')[0], n.split('_')[0].lower())  # `continue` is a Swift keyword
    out.append(f'    static let {name} = #"{js}"#')
out.append('}')
open(os.path.join(here, 'DermScholar', 'UtdScripts.swift'), 'w').write('\n'.join(out) + '\n')
print('ok')
